# Generated by Django 3.1.4 on 2021-02-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210224_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='company_name',
            new_name='organisation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
