# Generated by Django 3.1.4 on 2021-03-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20210303_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='decription',
            new_name='description',
        ),
    ]
